// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZPj7t9rRMGrHeUKH3o1oGKUFf_99DOPA',
    appId: '1:142066768072:web:aa0c469de4ebe43116adfd',
    messagingSenderId: '142066768072',
    projectId: 'workshop-5fb37',
    authDomain: 'workshop-5fb37.firebaseapp.com',
    storageBucket: 'workshop-5fb37.firebasestorage.app',
    measurementId: 'G-Z5C63TZGPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6NC1PG9J8EqF4haJKsYg5yQBDn3kLak4',
    appId: '1:142066768072:android:1548ba151db94ee316adfd',
    messagingSenderId: '142066768072',
    projectId: 'workshop-5fb37',
    storageBucket: 'workshop-5fb37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWCDbk92rmHTgjyKPMaHBocRjxonuji04',
    appId: '1:142066768072:ios:814382b6c9cfc02016adfd',
    messagingSenderId: '142066768072',
    projectId: 'workshop-5fb37',
    storageBucket: 'workshop-5fb37.firebasestorage.app',
    iosBundleId: 'com.example.workshopSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWCDbk92rmHTgjyKPMaHBocRjxonuji04',
    appId: '1:142066768072:ios:814382b6c9cfc02016adfd',
    messagingSenderId: '142066768072',
    projectId: 'workshop-5fb37',
    storageBucket: 'workshop-5fb37.firebasestorage.app',
    iosBundleId: 'com.example.workshopSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZPj7t9rRMGrHeUKH3o1oGKUFf_99DOPA',
    appId: '1:142066768072:web:3fc57ebb4a12996916adfd',
    messagingSenderId: '142066768072',
    projectId: 'workshop-5fb37',
    authDomain: 'workshop-5fb37.firebaseapp.com',
    storageBucket: 'workshop-5fb37.firebasestorage.app',
    measurementId: 'G-0QHTM4HG9Z',
  );

}